version: "3.5"
services:
  php:
    build:
      dockerfile: .docker/php/Dockerfile
      context: .
    volumes:
      - ./:/var/www/html
    ports:
      - 8000:80
    networks:
      - queue
  composer:
    image: composer:latest
    volumes:
        - ./:/app
        - ./.composer:/composer
  beanstalk:
    image: schickling/beanstalkd:latest
    networks:
      - queue
  mariadb:
    image: mariadb:latest
    env_file:
      - .env
    
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=user
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - queue
  
networks:
  queue:

